name: fyrbrowser
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_cef: ^0.2.2
  window_manager: ^0.3.7
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  flutter_svg: ^2.2.4
  path: ^1.8.3
  intl: ^0.18.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: San Francisco
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
